title: ATOM3D - Tasks on Molecules in Three Dimensions
description: A collection of benchmark datasets for machine learning in structural biology
logo: /atom3d-03.jpg
theme: jekyll-theme-minimal
collections:
  - staff_members
