name: cormorant
channels:
  - pytorch
  - conda-forge
  - defaults
  - omnia
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py37_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.10.0=he983fc9_1
  - intel-openmp=2019.4=243
  - joblib=0.14.1=py_0
  - jpeg=9c=h14c3975_1001
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.8.0=14_openblas
  - libcblas=3.8.0=14_openblas
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_4
  - libgomp=9.2.0=h24d8f2e_2
  - liblapack=3.8.0=14_openblas
  - libopenblas=0.3.7=h5ec1e0e_6
  - libpng=1.6.37=hed695b0_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - lz4-c=1.8.3=he1b5a44_1001
  - mkl=2019.4=243
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.9.0=hc9558a2_1
  - numpy=1.17.3=py37h95a1406_0
  - olefile=0.46=py_0
  - openssl=1.1.1d=h516909a_0
  - pillow=7.0.0=py37hefe7db6_0
  - pip=19.3.1=py37_0
  - python=3.7.6=h357f687_2
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - readline=8.0=hf8c457e_0
  - scikit-learn=0.22.1=py37hcdab131_1
  - scipy=1.4.1=py37h921218d_0
  - setuptools=45.0.0=py37_1
  - six=1.14.0=py37_0
  - sqlite=3.30.1=hcee41ef_0
  - tk=8.6.10=hed695b0_0
  - torchvision=0.5.0=py37_cu101
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
prefix: /home/users/mvoegele/miniconda3/envs/cormorant

