name: geometric
channels:
  - pytorch
  - conda-forge
  - rdkit
  - deepchem
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - blas=1.0=mkl
  - bleach=3.1.4=pyh9f0ad1d_0
  - boost=1.63.0=py36h415b752_1
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.4.5.1=hecc5488_0
  - cairo=1.16.0=hcf35c78_1003
  - certifi=2020.4.5.1=py36h9f0ad1d_0
  - cudatoolkit=10.2.89=hfd86e86_0
  - dbus=1.13.6=he372182_0
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36h9f0ad1d_1001
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=h86ecdb6_1001
  - freetype=2.10.1=he06d7ca_0
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.64.2=h6f030ca_0
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - icu=64.2=he1b5a44_1
  - importlib-metadata=1.6.0=py36h9f0ad1d_0
  - importlib_metadata=1.6.0=0
  - ipykernel=5.2.1=py36h95af2a2_0
  - ipython=7.13.0=py36h9f0ad1d_2
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - jedi=0.17.0=py36h9f0ad1d_0
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9c=h14c3975_1001
  - jsonschema=3.2.0=py36h9f0ad1d_1
  - jupyter=1.0.0=py_2
  - jupyter_client=6.1.3=py_0
  - jupyter_console=6.1.0=py_1
  - jupyter_core=4.6.3=py36h9f0ad1d_1
  - ld_impl_linux-64=2.34=h53a641e_0
  - libclang=9.0.1=default_hde54327_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libiconv=1.15=h516909a_1006
  - libllvm9=9.0.1=he513fc3_1
  - libpng=1.6.37=hed695b0_1
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc7e4089_6
  - libuuid=2.32.1=h14c3975_1000
  - libwebp-base=1.1.0=h516909a_3
  - libxcb=1.13=h14c3975_1002
  - libxkbcommon=0.10.0=he1b5a44_0
  - libxml2=2.9.10=hee79883_0
  - llvm-openmp=10.0.0=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_0
  - markupsafe=1.1.1=py36h8c4c3a4_1
  - mistune=0.8.4=py36h8c4c3a4_1001
  - mkl=2019.5=281
  - mkl-service=2.3.0=py36h516909a_0
  - mkl_fft=1.1.0=py36hc1659b7_1
  - mkl_random=1.1.0=py36hd6b4f25_0
  - nbconvert=5.6.1=py36h9f0ad1d_1
  - nbformat=5.0.6=py_0
  - ncurses=6.1=hf484d3e_1002
  - ninja=1.10.0=hc9558a2_0
  - notebook=6.0.3=py36_0
  - nspr=4.25=he1b5a44_0
  - nss=3.47=he751ad9_0
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - olefile=0.46=py_0
  - openssl=1.1.1g=h516909a_0
  - pandas=1.0.3=py36h830a2c2_1
  - pandoc=2.9.2.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.0=pyh9f0ad1d_0
  - pcre=8.44=he1b5a44_0
  - pexpect=4.8.0=py36h9f0ad1d_1
  - pickleshare=0.7.5=py36h9f0ad1d_1001
  - pillow=7.1.2=py36h8328e55_0
  - pip=20.0.2=py_2
  - pixman=0.38.0=h516909a_1003
  - prometheus_client=0.7.1=py_0
  - prompt-toolkit=3.0.5=py_0
  - prompt_toolkit=3.0.5=0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - pygments=2.6.1=py_0
  - pyqt=5.12.3=py36hcca6a23_1
  - pyrsistent=0.16.0=py36h8c4c3a4_0
  - python=3.6.10=h8356626_1011_cpython
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pytorch=1.5.0=py3.6_cuda10.2.89_cudnn7.6.5_0
  - pytz=2020.1=pyh9f0ad1d_0
  - pyzmq=19.0.0=py36h9947dbf_1
  - qt=5.12.5=hd8c4c69_1
  - qtconsole=4.7.3=pyh9f0ad1d_0
  - qtpy=1.9.0=py_0
  - rdkit=2017.09.1=py36_1
  - readline=8.0=hf8c457e_0
  - send2trash=1.5.0=py_0
  - setuptools=46.1.3=py36h9f0ad1d_0
  - six=1.14.0=py_1
  - sqlite=3.30.1=hcee41ef_0
  - terminado=0.8.3=py36h9f0ad1d_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hed695b0_0
  - torchvision=0.6.0=py36_cu102
  - tornado=6.0.4=py36h8c4c3a4_1
  - traitlets=4.3.3=py36h9f0ad1d_1
  - wcwidth=0.1.9=pyh9f0ad1d_0
  - webencodings=0.5.1=py_1
  - wheel=0.34.2=py_1
  - widgetsnbextension=3.5.1=py36_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_0
  - zeromq=4.3.2=he1b5a44_2
  - zipp=3.1.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
  - pip:
    - chardet==3.0.4
    - cycler==0.10.0
    - future==0.18.2
    - googledrivedownloader==0.4
    - h5py==2.10.0
    - idna==2.9
    - imageio==2.8.0
    - isodate==0.6.0
    - joblib==0.14.1
    - kiwisolver==1.2.0
    - llvmlite==0.32.0
    - matplotlib==3.2.1
    - networkx==2.4
    - numba==0.49.0
    - plyfile==0.7.2
    - pyparsing==2.4.7
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pywavelets==1.1.1
    - rdflib==5.0.0
    - requests==2.23.0
    - scikit-image==0.16.2
    - scikit-learn==0.22.2.post1
    - scipy==1.4.1
    - torch-cluster==1.5.4
    - torch-geometric==1.4.3
    - torch-scatter==2.0.4
    - torch-sparse==0.6.2
    - torch-spline-conv==1.2.0
    - urllib3==1.25.9
prefix: /home/martin/anaconda3/envs/geometric

